[app]
build_directory = "./"
sdk = "C"
devices = ["apex_p", "nanox", "nanos+", "stax", "flex"]

[use_cases]
use_test_keys = "EIP7702_TEST_WHITELIST=1"
dbg_use_test_keys = "DEBUG=1 EIP7702_TEST_WHITELIST=1"
memory_profiling = "DEBUG=1 EIP7702_TEST_WHITELIST=1 MEMORY_PROFILING=1"
dbg_no_checks = "DEBUG=1 BYPASS_SIGNATURES=1 CHALLENGE_NO_CHECK=1"
dbg_no_checks_profiling = "DEBUG=1 BYPASS_SIGNATURES=1 CHALLENGE_NO_CHECK=1 MEMORY_PROFILING=1"

[tests]
unit_directory = "./tests/unit"
pytest_directory = "./tests/ragger"
